## Notes from <Building Machine Learning System with Python>

### Ch1. Getting started with python machine learning

Numpy is optimized, which means it avoids copies wherever possible. See the following example.

In [1]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [2]:
b = a.reshape((3,2))
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
b[1][0] = 77
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [4]:
a

array([ 0,  1, 77,  3,  4,  5])

Even you just want to modify `b`, `a` is also changed. Whenever you need a true copy, you need to do the folllowing.

In [5]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [6]:
c = a.reshape((3,2)).copy()
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
c[1][0] = 77
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [8]:
a

array([0, 1, 2, 3, 4, 5])