## Notes from [Hackerrank](www.hackerrank.com) and [Python for everybody](https://www.coursera.org/specializations/python)

## 1. Introduction
### 1.1 Data type

The defualt division in python 2 is integer division. To make float division the default division, we need `from __future__ import division`.

Change a list of strings to numbers: `map(float, my_list)`

print format:{0:.2f}.format() see [detail](https://docs.python.org/2/tutorial/inputoutput.html)

** List **

In [21]:
a = [1, 4, 5, 2, 2]
a.append(10)         # append 10
print a
a.extend([20, 30])   # add another list
print a
a.insert(1, 'a')     # insert 'a' at 2nd position
print a
a.remove('a')        # remove 'a'
print a
a.pop(1)             # remove the 2nd element
print a
a.pop()              # if not parameter provided, it will remove the last element
print a
print a.index(5)     # return the first index of the parameter
print a.count(2)     # return the occurence of parameter
print a.reverse()    # reverse the list, return None
print a
print a.sort()       # sort the list, return None
print a
b = a[:]             # make a copy of list, if a changes, b will NOT change. 
c = a                # make aliasing of list, if a changes, c will change too.
print c
a[0] = 100
print c
print b

[1, 4, 5, 2, 2, 10]
[1, 4, 5, 2, 2, 10, 20, 30]
[1, 'a', 4, 5, 2, 2, 10, 20, 30]
[1, 4, 5, 2, 2, 10, 20, 30]
[1, 5, 2, 2, 10, 20, 30]
[1, 5, 2, 2, 10, 20]
1
2
None
[20, 10, 2, 2, 5, 1]
None
[1, 2, 2, 5, 10, 20]
[1, 2, 2, 5, 10, 20]
[100, 2, 2, 5, 10, 20]
[1, 2, 2, 5, 10, 20]


** Tuple **

Tuple is similar as list, but it's immutable.

In [24]:
a = (1, 2, 4)        # one way of initializing a tuple
b = tuple('abc')     # another way of initializing 
a, b = b, a          # You cannot change the element of tuple, but you can redefine them
print a
print b

('a', 'b', 'c')
(1, 2, 4)


** Set **

Set is the real set, like the mathematical concept.

In [30]:
a = {1, 2, 3, 4, 4}      # one way of initializing set
b = set([2, 3, 4, 5,5])  # Another way of initializing
print a, b
a.add('m')               # add elements
a.update('n')            # add elements
print a
a.discard('m')           # remove elements
a.remove('n')            # remove elements
print a
print a.union(b)               # union a and b, a and b don't change
print a.difference(b)          # difference between a and b
print a.intersection(b)        # intersect between a and b
print a, b

set([1, 2, 3, 4]) set([2, 3, 4, 5])
set([1, 2, 3, 4, 'm', 'n'])
set([1, 2, 3, 4])
set([1, 2, 3, 4, 5])
set([1])
set([2, 3, 4])
set([1, 2, 3, 4]) set([2, 3, 4, 5])


** Dict **

Dict uses hash table for `in` method, so it's much faster than list.

In [37]:
a = dict()                # initalize an empty dict
b = {'a': 1, 'b': 2}      # initalize another dict
a['c'] = 3
print a, b
print b.get('c', 0)       # if c in b, return b['c'], otherwise return 0
print b.items()           # return a list of tuples

for x in b:               # one way of going through the dict
    print x, b[x]

{'c': 3} {'a': 1, 'b': 2}
0
[('a', 1), ('b', 2)]
a 1
b 2


** String **

String is also immutable. You cannot change an element of a string.

[String functions](https://docs.python.org/2/library/string.html)

In [48]:
a = 'absdef'              # one way of changing a string
b = list(a)
b[2] = 'c'
a = ''.join(b)
print a

a = 'absdef'              # another way of changing a string
a = a[:2] + 'c' + a[3:]
print a

print a.capitalize()      # Capitalize first letter, but a doesn't change
print a
a = 'abcdefd'
print a.find('d')         # return the lowest index
print a.rfind('d')        # return the largest index
print a.index('d')        # like find(), but return error if 'd' doesn't exist
print a.rindex('d')       # similar as rfind()
print a.count('d')        # count occurrence 

a = 'AbcDef'
print a.lower()           # lowercase 
print a.upper()           # uppercase
print a.swapcase()        # convert case

a = 'ab cd'
print a.split()           # split into a list
print ''.join(a.split())  # join the string

a = ' dd ff '
print a.lstrip()          # Return the string, but remove left leading space
print a.rstrip()          # Return the string, but remove the right space
print a.strip()           # Return the string, but remove both
print a.replace('d', 'c') # replace element



abcdef
abcdef
Abcdef
abcdef
3
6
3
6
2
abcdef
ABCDEF
aBCdEF
['ab', 'cd']
abcd
dd ff 
 dd ff
dd ff
 cc ff 


In [3]:
b[1][0] = 77
b

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [4]:
a

array([ 0,  1, 77,  3,  4,  5])

Even you just want to modify `b`, `a` is also changed. Whenever you need a true copy, you need to do the folllowing.

In [5]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [6]:
c = a.reshape((3,2)).copy()
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
c[1][0] = 77
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [8]:
a

array([0, 1, 2, 3, 4, 5])