## Linear Algebra

In [1]:
import numpy as np
A = np.identity(3)
A

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [2]:
B = np.ones((3,3))
B

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [3]:
np.linalg.norm(A)

1.7320508075688772

In [4]:
import numpy as np
from scipy.linalg import inv, solve, det
A = ((1, 2), (3, 4))
A = np.array(A)
y = np.ones((2, 1))
det(A)

-2.0

In [8]:
np.dot(A, np.dot(inv(A), y))

array([[ 1.],
       [ 1.]])

In [6]:
solve(A, y)  # solve Ax=y

array([[-1.],
       [ 1.]])

In [9]:
# Calcualte eig value and eig vector
import numpy as np
from scipy.linalg import eig
A = ((1, 2),
    (2, 1))
A = np.array(A)
evals, evecs = eig(A)

## Finite Markov Chains

In [2]:
from quantecon import DiscreteRV
psi = (0.1, 0.9)      # probabilities over sample space {0, 1}
d = DiscreteRV(psi)
d.draw(5)             # generate 5 independent draws from psi

array([1, 0, 1, 1, 0])

In [3]:
import numpy as np
import quantecon as qe

def mc_sample_path(P, init=0, sample_size=1000):
    # === make sure P is a NumPy array === #
    P = np.asarray(P)
    # === allocate memory === #
    X = np.empty(sample_size, dtype=int)
    X[0] = init
    # === convert each row of P into a distribution === #
    # In particular, P_dist[i] = the distribution corresponding to P[i,:]
    n = len(P)
    P_dist = [qe.DiscreteRV(P[i,:]) for i in range(n)]

    # === generate the sample path === #
    for t in range(sample_size - 1):
        X[t+1] = P_dist[X[t]].draw()

    return X

P = [[0.4, 0.6], [0.2, 0.8]]
X = mc_sample_path(P, sample_size=100000)
np.mean(X == 0)

0.24897

In [13]:
# An example of simulating Markov chains
import numpy as np
import quantecon as qe
P = [[0.4, 0.6], [0.2, 0.8]]
mc = qe.MarkovChain(P)
X = mc.simulate(ts_length=1000000)
np.mean(X == 0)

0.24907000000000001

In [14]:
import quantecon as qe
P = [[0.9, 0.1, 0.0],
     [0.4, 0.4, 0.2],
     [0.1, 0.1, 0.8]]
mc = qe.MarkovChain(P)
mc.is_irreducible

True

In [15]:
P = [[0.4, 0.6], [0.2, 0.8]]
mc = qe.MarkovChain(P)
mc.stationary_distributions

array([[ 0.25,  0.75]])